require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion:
    3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - Gemfile
    - vendor/**/*
    - db/**

# Style Cops

Style/Documentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Metrics Cops

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Offense

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
   Enabled: false
